project:
  type: website
  output-dir: docs

website:
  title: "Mini Curso Quarto Github Pages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://jornadas-estadistica.github.io/
        text: JIE-2024

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false